name: docs
on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Typst
        run: |
          wget https://github.com/typst/typst/releases/download/v0.11.0/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst-x86_64-unknown-linux-musl.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
          typst --version
      
      - name: Build PDF
        run: |
          cd docs
          typst compile info.md info.pdf
      
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: datasheet
          path: docs/info.pdf
